kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: python:3.13
    commands:
      - echo "My secret is: $MY_TEST_KEY"
      - pip install -r requirements.txt || true
    environment:
      MY_TEST_KEY:
        from_secret: MY_TEST_KEY

  - name: test
    image: python:3.13
    commands:
      - python -m pytest -q || python test_app.py

trigger:
  event:
    - push
