kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: python:3.13
    environment:
      MY_TEST_KEY:
        from_secret: my_test_key
    commands:
      - echo "My secret is:"
      - echo $MY_TEST_KEY
      - echo "For security reasons, you will see asteriks '*******' instead the value under the echo command."
      - pip install -r requirements.txt || true

  - name: test
    image: python:3.13
    commands:
      - python -m pytest -q || python test_app.py

  - name: notify-telegram
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: TELEGRAM_TOKEN
      to: 
        from_secret: TELEGRAM_TO
      message: "Build {{build.number}} on {{repo.name}} is {{build.status}}! Link: {{build.link}}"
    when:
      status: [ success, failure ]

trigger:
  event:
    - push
